### ISSUE TITLE
crash when navigation

### ISSUE THREAD

**Issue by mahmooddagga** [aurelhubert/ahbottomnavigation#177]
```
        org.fingerlinks.mobile.android.navigator.NavigatorException: Building request with dead context[Activity finished]



                                                                 org.fingerlinks.mobile.android.navigator.NavigatorException: Building request with dead context[Activity finished]
                                                                     at org.fingerlinks.mobile.android.navigator.builder.impl.BaseBuilder.<init>(BaseBuilder.java:23)
                                                                     at org.fingerlinks.mobile.android.navigator.builder.impl.GoToBuilder.<init>(GoToBuilder.java:24)
                                                                     at org.fingerlinks.mobile.android.navigator.Navigator.build(Navigator.java:38)
                                                                     at com.android...Activity.MainActivity$1.onTabSelected(MainActivity.java:144)
                                                                     at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.updateSmallItems(AHBottomNavigation.java:663)
                                                                     at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.access$100(AHBottomNavigation.java:46)
                                                                     at com.aurelhubert.ahbottomnavigation.AHBottomNavigation$3.onClick(AHBottomNavigation.java:497)
                                                                     at android.view.View.performClick(View.java:4654)
                                                                     at android.view.View$PerformClick.run(View.java:19438)
                                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:146)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5602)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by aurelhubert** [comment]
It seems that the crashs appears in your code, more precisely here:
```java
com.android...Activity.MainActivity$1.onTabSelected(MainActivity.java:144)
```
