### ISSUE TITLE
Exception android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class TextView

### ISSUE THREAD

**Issue by LalitDB** [aurelhubert/ahbottomnavigation#258]
android.view.LayoutInflater.inflate (LayoutInflater.java:539)
android.view.LayoutInflater.inflate (LayoutInflater.java:423)
com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createClassicItems (AHBottomNavigation.java:381)
com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems (AHBottomNavigation.java:261)
com.aurelhubert.ahbottomnavigation.AHBottomNavigation.onSizeChanged (AHBottomNavigation.java:147)
android.view.View.sizeChange (View.java:17112)
android.view.View.setFrame (View.java:17074)
android.view.View.layout (View.java:16966)
android.view.ViewGroup.layout (ViewGroup.java:5590)
android.support.design.widget.CoordinatorLayout.layoutChild (CoordinatorLayout.java:1167)
android.support.design.widget.CoordinatorLayout.onLayoutChild (CoordinatorLayout.java:852)
android.support.design.widget.CoordinatorLayout.onLayout (CoordinatorLayout.java:871)
android.view.View.layout (View.java:16975)
android.view.ViewGroup.layout (ViewGroup.java:5590)
android.widget.FrameLayout.layoutChildren (FrameLayout.java:396)
android.widget.FrameLayout.onLayout (FrameLayout.java:333)
android.view.View.layout (View.java:16975)
android.view.ViewGroup.layout (ViewGroup.java:5590)
android.widget.LinearLayout.setChildFrame (LinearLayout.java:2001)
android.widget.LinearLayout.layoutVertical (LinearLayout.java:1844)
android.widget.LinearLayout.onLayout (LinearLayout.java:1753)
android.view.View.layout (View.java:16975)
android.view.ViewGroup.layout (ViewGroup.java:5590)
android.widget.FrameLayout.layoutChildren (FrameLayout.java:396)
android.widget.FrameLayout.onLayout (FrameLayout.java:333)
android.view.View.layout (View.java:16975)
android.view.ViewGroup.layout (ViewGroup.java:5590)
android.widget.LinearLayout.setChildFrame (LinearLayout.java:2001)
android.widget.LinearLayout.layoutVertical (LinearLayout.java:1844)
android.widget.LinearLayout.onLayout (LinearLayout.java:1753)
android.view.View.layout (View.java:16975)
android.view.ViewGroup.layout (ViewGroup.java:5590)
android.widget.FrameLayout.layoutChildren (FrameLayout.java:396)
android.widget.FrameLayout.onLayout (FrameLayout.java:333)
com.android.internal.policy.PhoneWindow$DecorView.onLayout (PhoneWindow.java:2782)
android.view.View.layout (View.java:16975)
android.view.ViewGroup.layout (ViewGroup.java:5590)
android.view.ViewRootImpl.performLayout (ViewRootImpl.java:2556)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2259)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1325)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6741)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:912)
android.view.Choreographer.doCallbacks (Choreographer.java:714)
android.view.Choreographer.doFrame (Choreographer.java:649)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:898)
android.os.Handler.handleCallback (Handler.java:815)
android.os.Handler.dispatchMessage (Handler.java:104)
android.os.Looper.loop (Looper.java:207)
android.app.ActivityThread.main (ActivityThread.java:5769)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:789)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:679)

**Comment by kenumir** [comment]
I have reported same error.
Device: LG LG-H635, Android 6.0.
Happens on user device, cannot reproduce on my devices.

**Comment by aurelhubert** [comment]
That's a bit light to understand where the crash happens... Can you provide more details?

**Comment by kenumir** [comment]
Similar error o device HTC Desire 816, android 6.0
Stack trace:

> android.view.InflateException: Binary XML file line #35: Binary XML file line #35: Error inflating class TextView
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
>         at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createClassicItems(AHBottomNavigation.java:381)
>         at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems(AHBottomNavigation.java:261)
>         at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.onSizeChanged(AHBottomNavigation.java:147)
>         at android.view.View.sizeChange(View.java:16849)
>         at android.view.View.setFrame(View.java:16811)
>         at android.view.View.layout(View.java:16720)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2728)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2288)
>         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2025)
>         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1174)
>         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6241)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:676)
>         at android.view.Choreographer.doFrame(Choreographer.java:606)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
>         at android.os.Handler.handleCallback(Handler.java:739)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at android.os.Looper.loop(Looper.java:168)
>         at android.app.ActivityThread.main(ActivityThread.java:5845)
>         at java.lang.reflect.Method.invoke(Method.java:-2)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
> Caused by: android.view.InflateException: Binary XML file line #35: Error inflating class TextView
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
>         at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createClassicItems(AHBottomNavigation.java:381)
>         at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems(AHBottomNavigation.java:261)
>         at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.onSizeChanged(AHBottomNavigation.java:147)
>         at android.view.View.sizeChange(View.java:16849)
>         at android.view.View.setFrame(View.java:16811)
>         at android.view.View.layout(View.java:16720)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2728)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2288)
>         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2025)
>         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1174)
>         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6241)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:676)
>         at android.view.Choreographer.doFrame(Choreographer.java:606)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
>         at android.os.Handler.handleCallback(Handler.java:739)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at android.os.Looper.loop(Looper.java:168)
>         at android.app.ActivityThread.main(ActivityThread.java:5845)
>         at java.lang.reflect.Method.invoke(Method.java:-2)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.content.res.StringBlock.get(int)' on a null object reference
>         at android.content.res.AssetManager.getPooledStringForCookie(AssetManager.java:295)
>         at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:1156)
>         at android.content.res.TypedArray.getValueAt(TypedArray.java:1142)
>         at android.content.res.TypedArray.getDrawable(TypedArray.java:865)
>         at android.view.View.<init>(View.java:3961)
>         at android.widget.TextView.<init>(TextView.java:680)
>         at android.widget.TextView.<init>(TextView.java:674)
>         at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
>         at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
>         at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
>         at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
>         at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
>         at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
>         at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createClassicItems(AHBottomNavigation.java:381)
>         at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems(AHBottomNavigation.java:261)
>         at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.onSizeChanged(AHBottomNavigation.java:147)
>         at android.view.View.sizeChange(View.java:16849)
>         at android.view.View.setFrame(View.java:16811)
>         at android.view.View.layout(View.java:16720)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
>         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
>         at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2728)
>         at android.view.View.layout(View.java:16727)
>         at android.view.ViewGroup.layout(ViewGroup.java:5452)
>         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2288)
>         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2025)
>         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1174)
>         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6241)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:676)
>         at android.view.Choreographer.doFrame(Choreographer.java:606)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
>         at android.os.Handler.handleCallback(Handler.java:739)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at android.os.Looper.loop(Looper.java:168)
>         at android.app.ActivityThread.main(ActivityThread.java:5845)
>         at java.lang.reflect.Method.invoke(Method.java:-2)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by AttITuder** [comment]
android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class <unknown>
                                                             Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
                                                             Caused by: java.lang.reflect.InvocationTargetException
                                                                 at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:656)
                                                                 at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64)
                                                                 at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:107)
                                                                 at android.view.LayoutInflater.onCreateView(LayoutInflater.java:728)
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:796)
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                 at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createClassicItems(AHBottomNavigation.java:402)
                                                                 at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems(AHBottomNavigation.java:282)
                                                                 at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.onSizeChanged(AHBottomNavigation.java:150)
                                                                 at android.view.View.sizeChange(View.java:17806)
                                                                 at android.view.View.setFrame(View.java:17768)
                                                                 at android.view.View.layout(View.java:17685)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                                 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                 at android.view.View.layout(View.java:17688)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                 at android.view.View.layout(View.java:17688)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
                                                                 at android.view.View.layout(View.java:17688)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                                 at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.onLayout(CustomViewAbove.java:582)
                                                                 at android.view.View.layout(View.java:17688)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                                 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                 at android.view.View.layout(View.java:17688)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                 at com.android.internal.policy.DecorView.onLayout(DecorView.java:774)
                                                                 at android.view.View.layout(View.java:17688)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5631)
                                                                 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2513)
                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2228)
                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1366)
                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6768)
                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:735)
                                                                 at android.view.Choreographer.doFrame(Choreographer.java:667)
                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
                                                                 at android.os.Handler.handleCallback(Handler.java:761)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                 at android.os.Looper.loop(Looper.java:156)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                              Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0100c9 a=-1}

**Comment by carlosalexandresmo** [comment]
it occurred 
Caused by java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
       at android.util.ContainerHelpers.binarySearch + 47(ContainerHelpers.java:47)
       at android.util.LongSparseArray.get + 113(LongSparseArray.java:113)
       at android.util.LongSparseArray.get + 104(LongSparseArray.java:104)
       at android.graphics.Typeface.create + 193(Typeface.java:193)
       at android.graphics.Typeface.create + 143(Typeface.java:143)
       at android.widget.TextView.setTypefaceFromAttrs + 1659(TextView.java:1659)
       at android.widget.TextView.<init> + 1468(TextView.java:1468)
       at android.widget.TextView.<init> + 742(TextView.java:742)
       at androidx.appcompat.widget.AppCompatTextView.<init> + 87(AppCompatTextView.java:87)
       at androidx.appcompat.widget.AppCompatTextView.<init> + 83(AppCompatTextView.java:83)
       at androidx.appcompat.app.AppCompatViewInflater.createTextView + 177(AppCompatViewInflater.java:177)
       at androidx.appcompat.app.AppCompatViewInflater.createView + 102(AppCompatViewInflater.java:102)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView + 1266(AppCompatDelegateImpl.java:1266)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView + 1316(AppCompatDelegateImpl.java:1316)
       at android.view.LayoutInflater.createViewFromTag + 769(LayoutInflater.java:769)
       at android.view.LayoutInflater.createViewFromTag + 727(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate + 858(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren + 821(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate + 518(LayoutInflater.java:518)
       at android.view.LayoutInflater.inflate + 426(LayoutInflater.java:426)
       at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createClassicItems + 405(AHBottomNavigation.java:405)
       at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems + 282(AHBottomNavigation.java:282)
       at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.onSizeChanged + 151(AHBottomNavigation.java:151)
       at android.view.View.sizeChange + 17682(View.java:17682)
       at android.view.View.setFrame + 17644(View.java:17644)
       at android.view.View.layout + 17561(View.java:17561)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild + 1183(CoordinatorLayout.java:1183)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild + 870(CoordinatorLayout.java:870)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout + 889(CoordinatorLayout.java:889)
       at android.view.View.layout + 17564(View.java:17564)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at android.widget.FrameLayout.layoutChildren + 323(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout + 261(FrameLayout.java:261)
       at android.view.View.layout + 17564(View.java:17564)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at android.widget.LinearLayout.setChildFrame + 1741(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical + 1585(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout + 1494(LinearLayout.java:1494)
       at android.view.View.layout + 17564(View.java:17564)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at android.widget.FrameLayout.layoutChildren + 323(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout + 261(FrameLayout.java:261)
       at android.view.View.layout + 17564(View.java:17564)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at android.widget.LinearLayout.setChildFrame + 1741(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical + 1585(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout + 1494(LinearLayout.java:1494)
       at android.view.View.layout + 17564(View.java:17564)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at android.widget.FrameLayout.layoutChildren + 323(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout + 261(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout + 755(DecorView.java:755)
       at android.view.View.layout + 17564(View.java:17564)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at android.view.ViewRootImpl.performLayout + 2415(ViewRootImpl.java:2415)
       at android.view.ViewRootImpl.performTraversals + 2130(ViewRootImpl.java:2130)
       at android.view.ViewRootImpl.doTraversal + 1286(ViewRootImpl.java:1286)
       at android.view.ViewRootImpl$TraversalRunnable.run + 6551(ViewRootImpl.java:6551)
       at android.view.Choreographer$CallbackRecord.run + 871(Choreographer.java:871)
       at android.view.Choreographer.doCallbacks + 683(Choreographer.java:683)
       at android.view.Choreographer.doFrame + 619(Choreographer.java:619)
       at android.view.Choreographer$FrameDisplayEventReceiver.run + 857(Choreographer.java:857)
       at android.os.Handler.handleCallback + 751(Handler.java:751)
       at android.os.Handler.dispatchMessage + 95(Handler.java:95)
       at android.os.Looper.loop + 154(Looper.java:154)
       at android.app.ActivityThread.main + 6312(ActivityThread.java:6312)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 872(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main + 762(ZygoteInit.java:762)

**Comment by carlosalexandresmo** [comment]
Caused by java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
       at android.util.ContainerHelpers.binarySearch + 47(ContainerHelpers.java:47)
       at android.util.LongSparseArray.get + 113(LongSparseArray.java:113)
       at android.util.LongSparseArray.get + 104(LongSparseArray.java:104)
       at android.graphics.Typeface.create + 193(Typeface.java:193)
       at android.graphics.Typeface.create + 143(Typeface.java:143)
       at android.widget.TextView.setTypefaceFromAttrs + 1659(TextView.java:1659)
       at android.widget.TextView.<init> + 1468(TextView.java:1468)
       at android.widget.TextView.<init> + 742(TextView.java:742)
       at androidx.appcompat.widget.AppCompatTextView.<init> + 87(AppCompatTextView.java:87)
       at androidx.appcompat.widget.AppCompatTextView.<init> + 83(AppCompatTextView.java:83)
       at androidx.appcompat.app.AppCompatViewInflater.createTextView + 177(AppCompatViewInflater.java:177)
       at androidx.appcompat.app.AppCompatViewInflater.createView + 102(AppCompatViewInflater.java:102)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView + 1266(AppCompatDelegateImpl.java:1266)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView + 1316(AppCompatDelegateImpl.java:1316)
       at android.view.LayoutInflater.createViewFromTag + 769(LayoutInflater.java:769)
       at android.view.LayoutInflater.createViewFromTag + 727(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate + 858(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren + 821(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate + 518(LayoutInflater.java:518)
       at android.view.LayoutInflater.inflate + 426(LayoutInflater.java:426)
       at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createClassicItems + 405(AHBottomNavigation.java:405)
       at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems + 282(AHBottomNavigation.java:282)
       at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.onSizeChanged + 151(AHBottomNavigation.java:151)
       at android.view.View.sizeChange + 17682(View.java:17682)
       at android.view.View.setFrame + 17644(View.java:17644)
       at android.view.View.layout + 17561(View.java:17561)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild + 1183(CoordinatorLayout.java:1183)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild + 870(CoordinatorLayout.java:870)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout + 889(CoordinatorLayout.java:889)
       at android.view.View.layout + 17564(View.java:17564)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at android.widget.FrameLayout.layoutChildren + 323(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout + 261(FrameLayout.java:261)
       at android.view.View.layout + 17564(View.java:17564)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at android.widget.LinearLayout.setChildFrame + 1741(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical + 1585(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout + 1494(LinearLayout.java:1494)
       at android.view.View.layout + 17564(View.java:17564)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at android.widget.FrameLayout.layoutChildren + 323(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout + 261(FrameLayout.java:261)
       at android.view.View.layout + 17564(View.java:17564)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at android.widget.LinearLayout.setChildFrame + 1741(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical + 1585(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout + 1494(LinearLayout.java:1494)
       at android.view.View.layout + 17564(View.java:17564)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at android.widget.FrameLayout.layoutChildren + 323(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout + 261(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout + 755(DecorView.java:755)
       at android.view.View.layout + 17564(View.java:17564)
       at android.view.ViewGroup.layout + 5656(ViewGroup.java:5656)
       at android.view.ViewRootImpl.performLayout + 2415(ViewRootImpl.java:2415)
       at android.view.ViewRootImpl.performTraversals + 2130(ViewRootImpl.java:2130)
       at android.view.ViewRootImpl.doTraversal + 1286(ViewRootImpl.java:1286)
       at android.view.ViewRootImpl$TraversalRunnable.run + 6551(ViewRootImpl.java:6551)
       at android.view.Choreographer$CallbackRecord.run + 871(Choreographer.java:871)
       at android.view.Choreographer.doCallbacks + 683(Choreographer.java:683)
       at android.view.Choreographer.doFrame + 619(Choreographer.java:619)
       at android.view.Choreographer$FrameDisplayEventReceiver.run + 857(Choreographer.java:857)
       at android.os.Handler.handleCallback + 751(Handler.java:751)
       at android.os.Handler.dispatchMessage + 95(Handler.java:95)
       at android.os.Looper.loop + 154(Looper.java:154)
       at android.app.ActivityThread.main + 6312(ActivityThread.java:6312)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 872(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main + 762(ZygoteInit.java:762)

**Comment by carlosalexandresmo** [comment]
@aurelhubert is occurring frequently with me in 2.3.4
