### ISSUE TITLE
NotFoundException 

### ISSUE THREAD

**Issue by samimw** [aurelhubert/ahbottomnavigation#418]
Am getting below error:

APP_VERSION_CODE=26
APP_VERSION_NAME=1.25
ANDROID_VERSION=6.0.1
PHONE_MODEL=XT1254
CUSTOM_DATA=
STACK_TRACE=android.content.res.Resources$NotFoundException: Resource ID #0x7f07008a
at android.content.res.Resources.getValue(Resources.java:1351)
at android.content.res.Resources.getDrawable(Resources.java:804)
at android.content.Context.getDrawable(Context.java:458)
at androidx.core.a.a.a(SourceFile:454)
at com.aurelhubert.ahbottomnavigation.AHBottomNavigationItem.getDrawable(SourceFile:133)
at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createClassicItems(SourceFile:411)
at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems(SourceFile:282)
at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.onSizeChanged(SourceFile:151)

**Comment by samimw** [comment]
Anyone??? I still get these errors...
